export const FORM_PROJECT = "FORM_PROJECT";
export const GET_PROJECT = "GET_PROJECT";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const VALIDATE_FORM  = "VALIDATE_FORM";
export const GET_CURRENT_PROJECT  = "GET_CURRENT_PROJECT";
export const DELETE_PROJECT  = "DELETE_PROJECT";
